### ISSUE TITLE
Move the "Installation" step to the end of the table of contents

### ISSUE THREAD

**Issue by sesh** [DjangoGirls/tutorial#1014]
Hi all,

During out workshop in Melbourne today several of the participants navigated directly from the Introduction to the Installation step. This definitely slows down the progress as people end up installing everything up front instead of doing it as they move through the tutorial.

Is there a reason why this is listed as the second step? If not, I'd be happy to put together PR to move it to the bottom.

**Comment by aniav** [comment]
Hey @sesh the idea of the installation chapter has come up from different Django Girls events. At some point most of the events had an installation party, where people would come and just do the installation so they have the environment prepared for the next day and can start it from the same point.

It is also stated at the beginning of the installation chapter. Therefore I am not up for moving the chapter to the end of the tutorial, it wouldn't be a good move in my opinion.

Maybe we could rearrange information at the top of the installation chapter so people would have to decide upon it if they should progress with it?

**Comment by sesh** [comment]
@aniav I think adding a clear message at the start of the installation chapter that explains that you have a choice between doing it "up front" or "as you go" would be good. This could indicate to people that they can ask their coaches which approach they suggest if they are at an event.

For our event - we really wanted the participants to install as they went for a variety of reasons (the somewhat poor internet connection, being one). In hindsight we could have easily solved this by just mentioning to people that they can skip the installation step. Personally my feeling is that if you're not at an installation evening, it makes more sense to do the installation as-you-go since it means that you get into the learning parts of the tutorial much quicker

**Comment by humitos** [comment]
@aniav we agree with you. We had the same problem in most of our Django Girls workshops: people start at Installation chapter and I have to go table by table explaining that section had to be done at home (was in the confirmation email) and now has to be omitted.

We finally end moving that section as the last one (after "What's next?") in our version of the tutorial (we have a fork for the Spanish translation since it was out of date). Now, it's too much clear for attendees since they just start reading from the beginning and that's all. People that read the confirmation email carefully, just install everything from that section since it's linked in the email.

**Comment by aniav** [comment]
Moving the installation step to the end is not a solution. I looked into google analytics and 1) the tutorial is used mostly during weekdays 2) the numbers form analytics suggest that most of the users of the tutorial are online/non-workshop ones. So of course when you use the Spanish tutorial only during the workshops it's easier for you and your style of the workshops, but you have to understand that we have to prepare the tutorial to a broader audience. If I would say something about workshops in other countries - in Poland an installation party is a standard, or if we ask people to prepare at home (with better internet) they need to install everything beforehand and the installation chapter helps a lot. The installation chapter at the end of the tutorial would be completely omitted by people not accustomed with the tutorial. They would simply get to it at the end of going through the tutorial.

There are two important things here:
1. Organizers should stress out *to the coaches* that the installation chapter is only for installation party purposes, and if you don't have an installation party, you want to skip it.
2. The installation chapter should have a more visible indication that it's only for the installation party / for people who want everything setup in advance.

I am therefore not agreeing on moving the installation chapter to the end.

Also, please take a look at the issue from which the chapter came from: https://github.com/DjangoGirls/tutorial/issues/376

**Comment by humitos** [comment]
My last comment agrees with @aniav but I wanted to agree with @sesh :) . Sorry, about that.

> 1) the tutorial is used mostly during weekdays 2) the numbers form analytics suggest that most of the users of the tutorial are online/non-workshop ones

This fits perfectly with our solution to move the installation chapter to the end, because there is no need to install everything up front if you are at your home. In fact, that chapter says:

> If you're doing the tutorial at home, not at one of the Django Girls events, you can completely skip this chapter now and go straight to the How the Internet works chapter.

Regarding this,

> Organizers should stress out to the coaches that the installation chapter is only for installation party purposes, and if you don't have an installation party, you want to skip it.

This is an extra effort during the day, and some coaches get confused no matter how much stress the organizers put on that (I organized about 15 workshops in 5 different countries).

> if we ask people to prepare at home (with better internet) they need to install everything beforehand and the installation chapter helps a lot

We do this, but instead of linking the home of the tutorial, we link the exactly installation chapter, that's the only thing they have to do on their houses before attending the workshop (if there is no installation party)

> They would simply get to it at the end of going through the tutorial.

That's exactly what we want in the "normal flow" of the tutorial: read and install while your are going on. The "no normal flow" is install everything beforehand that should be the "corner case" that has to be explained in installation parties or by the confirmation email.

> The installation chapter should have a more visible indication that it's only for the installation party / for people who want everything setup in advance.

As this is a more relaxed environment since the most important objective is to install everything needed for the next day. It's easy to communicate that the only thing we have to do at that moment is to go to the installation chapter at the end and, when that chapter is finished, there is nothing else to do that day :)

**Comment by helenst** [comment]
@aniav What do you think about a separate install guide? As the person who put the install chapter there in the first place, I also have my doubts about it sometimes! For example, I've told people to work through the install section, but sometimes they've not known when to stop - e.g. telling them to "work through this page" - is the page the section, or the whole thing? I don't know how easy it would be to do though.

**Comment by jhodgdon-drp** [comment]
The text at the top that says to skip the installation chapter is under the "If you're doing the tutorial at home" section. This means that people attending a workshop would probably not pay attention to it.

So maybe what we could/should do is add another section called "If you are at a workshop", and there we could say that if there's an installation party, this page is useful for that, but otherwise, you should skip and install things as they are needed.

Another option would be to retitle the page to say something like "All at once installation", to make it clearer that's what it's for.

I'll make a PR with proposed text so we can have something concrete to discuss.
