### ISSUE TITLE
Opening files is a difficult concept

### ISSUE THREAD

**Issue by ekohl** [DjangoGirls/tutorial#1042]
I've noticed that many of my students have issues with opening files. The concept of a fileysystem and that files can be opened by multiple programs is foreign for many.

For example in https://github.com/DjangoGirls/tutorial/blob/master/en/django_models/README.md a student didn't understand that models.py needs to be opened in the text editor. My student double clicked and it opened in Python rather than Sublime.

I'm unsure what's the best way to solve this so I'm opening this issue.

**Comment by jhodgdon-drp** [comment]
I think this is a good point.

There is a good example of how this is explained in the "introduction to Python" chapter under "Save it!", which says:

Earlier, we picked out a code editor from the code editor section. We'll need to open the editor now and write some code into a new file:

And then it goes on to explain saving the file with a .py extension. I think this would be a good model to follow for the rest of the tutorial... although this is about creating a new file rather than opening an existing file.

Probably for the case of opening an existing file, we could say something like "Open the code editor you installed earlier, and open the file ___ in the editor." instead of language like

Let's open blog/models.py, remove everything from it, and write code like this:

that is currenty in the Django models page mentioned in this issue. It seems like we should go through the tutorial and see where all this needs to be done. Thoughts?

**Comment by jhodgdon-drp** [comment]
Another place where a file is "opened" and the code editor is not mentioned: in django_views, near the top under "blog/views.py", it says "OK, let's open up this file and see what's in there".

And in the previous page, django_urls, under blog.urls it says "Create a new empty file named urls.py..." without mentioning the code editor.

I'm reading through the rest and will add comments for other spots I find, then make a PR to fix them all...

**Comment by jhodgdon-drp** [comment]
Another spot that probably needs similar attention: in the css topic (and I think elsewhere?) it says "Then create a new file called ...". How do you do that? It should probably explain to open the code editor and create a new file within that.

**Comment by jhodgdon-drp** [comment]
I made a pull request, adding "in the code editor" to all the places I could fine where files were mentioned.

**Comment by ekohl** [comment]
Fixed in #1344
