### ISSUE TITLE
More info around pythonanywhere

### ISSUE THREAD

**Issue by no1joel** [DjangoGirls/tutorial#1074]
A couple of attendees were a little confused by pythonanywhere.
Firstly they were a little surprised at having to enter credit card details so perhaps a warning about that in the tutorial.
Secondly, people thought they maybe had to create the account on pythonanywhere to be able to use python, so maybe a short sentence or two to differentiate python and pythonanywhere.

**Comment by jhodgdon-drp** [comment]
It looks like the first part of this issue has been taken care of: the tutorial now recommends creating a "beginner" account on Python Anywhere, which (I just did it yesterday) does not require a credit card.

Regarding the second part, on the "Deploy" topic, there is currently text saying:

As you learned, a website has to be located on a server. There are a lot of server providers available on the internet, we're going to use PythonAnywhere. PythonAnywhere is free for small applications that don't have too many visitors so it'll definitely be enough for you now.

So that explains why you need Python Anywhere, if you are installing things by going through the tutorial step by step. But you don't see this text if you are on the one-page install everything guide.

I'll make a pull request that adds a note...

**Comment by jhodgdon-drp** [comment]
I decided it was better to add one sentence to the PythonAnywhere installation instructions, which are included both in the Deploy page and the Installation page. Pull request ready...
