### ISSUE TITLE
This tutorial is not translated to Pashto language.

### ISSUE THREAD

**Issue by Ubaidullah-Ismat** [DjangoGirls/tutorial#1283]
Pashto is widely spoken language in Afghanistan and Pakistan. I am native Pashto speaker,  I can help you to translate this tutorial.

**Comment by magul** [comment]
Added to Crowdin project: https://crowdin.com/project/django-girls-tutorial/ps#

Feel free to start translation. Closing this one.

**Comment by magul** [comment]
@goanpeca There's a issue opened by @das-g to describe this process: #1271.

My current aproach to handle translations is there:
* https://github.com/DjangoGirls/tutorial/issues/1271#issuecomment-392930428
* https://github.com/DjangoGirls/tutorial/issues/1271#issuecomment-392931759

Of course, I'm open to any discussion.

**Comment by goanpeca** [comment]
Thanks for pointing me in that direction, I appreciate it. Now whenever a change occurs in master it is pushed to crowdin, so any translations on that specific file, or paragraph (not sure how crowdin detects handles this) is lost, so that is has to be translated once again? is this a per diff thing or per file?

**Comment by magul** [comment]
Some way per sentence, but don't know how they define one.

**Comment by magul** [comment]
(BTW we should move this discussion to #1271 )

**Comment by magul** [comment]
@Ubaidullah-Ismat If You will have any difficulties with Crowdin, please let me know. We will try to provide You some support here.
