### ISSUE TITLE
"cd $USER.pythonanywhere.com" doesn't work for everyone

### ISSUE THREAD

**Issue by das-g** [DjangoGirls/tutorial#1474]
### Issue description

In [the re-deployment inststructions](https://tutorial.djangogirls.org/en/django_templates/#one-more-thing) in chapter "Django templates" we [currently let](https://github.com/DjangoGirls/tutorial/blame/51bd85d086567c3266dd4d215a8961f8d2c8051f/en/django_templates/README.md#L92) the user execute
```bash
cd $USER.pythonanywhere.com
```
on PythonAnywhere.

While this will change into the Git repository on PythonAnywhere for most users, it won't work for all. When a user has a PythonAnywhere username that isn't a valid domain name part (e.g. containing capital letters), the directory name will be different from the username + `.pythonanywhere.com`.

I'm not sure how to best resolve this. Should we change the instruction to
```bash
cd *.pythonanywhere.com
```
or try to imitate the username-to-subdomain conversion that `pa_autoconfigure_django.py` does?

Or is there some other environment variable or file that would tell us the correct repo name? (Maybe @hjwp knows?)

Or should we simply advice users to choose lowercase alphanumeric PythonAnywhere usernames?

### Language

(all)

### Operating system

n/a

**Comment by jhodgdon-drp** [comment]
Possible suggestion:

Leave the instructions as they are, but add a sentence afterwards saying something like:

Note that in some cases, your PythonAnywhere domain name might not start with exactly your user name (such as if your user name contains capital letters). So if this command doesn't work, use the `ls` command to find your actual domain/folder name, and then `cd` to there.

Also note that these same cd instructions appear in the deploy instructions in several places:
https://tutorial.djangogirls.org/en/html/
https://tutorial.djangogirls.org/en/django_templates/
https://tutorial.djangogirls.org/en/extend_your_application/
https://tutorial.djangogirls.org/en/django_forms/

So we should probably make that note the first time, and then later on use something like "yourdomainname" instead of "yourusername".

Thoughts? I can make a PR if this seems like a good idea.

**Comment by das-g** [comment]
> Leave the instructions as they are, but add a sentence afterwards saying something like:
> 
> >Note that in some cases, your PythonAnywhere domain name might not start with exactly your user name (such as if your user name contains capital letters). So if this command doesn't work, use the `ls` command to find your actual domain/folder name, and then `cd` to there.

Sounds good to me!

> I can make a PR

Please do. :smiley:

**Comment by das-g** [comment]
> Leave the instructions as they are, but add a sentence afterwards saying something like: [...]

I like that solution, because it
* doesn't add any more unexplained "magic" than we already have
* keeps the copy-paste comfort of the current code snippet for those for whom it works
* doesn't restrict choice of usernames any more than PythonAnywhere itself already does

**Comment by jhodgdon-drp** [comment]
PR made #1477
