### ISSUE TITLE
Translation :Urdu Language 

### ISSUE THREAD

**Issue by umarvinci** [DjangoGirls/tutorial#1507]
### Issue description

Describe what's the problem here.

### Language
Translation in urdu language is not there
Is this related to a specific language of the tutorial?

### Operating system

What operating system does this issue relate to?

**Comment by das-g** [comment]
Hi @umarvinci

> Translation in urdu language is not there

What do you mean by "is not there"?

On https://tutorial.djangogirls.org/, Urdu is not listed, because nobody has translated the tutorial to Urdu, yet. If you (and/or others) want to translate the tutorial to Urdu, we can add that language to [our Crowdin project](https://crowdin.com/project/django-girls-tutorial), so that you can collaborate on the translation there. Note that we won't list the translation on https://tutorial.djangogirls.org/ until it is complete and proofread.

Crowdin doesn't offer "Urdu" per-se, but only its two variants "Urdu (India)" and "Urdu (Pakistan)". Which one shall we add to Crowdin?

**Comment by umarvinci** [comment]
Hi
Thank you for your reply. I would request to add urdu India version.

Regards
Umar

**Comment by magul** [comment]
Done: https://crowdin.com/project/django-girls-tutorial/ur-IN
