### ISSUE TITLE
Why not update the Django version of the tutorial?

### ISSUE THREAD

**Issue by kaizumaki** [DjangoGirls/tutorial#1555]
### Issue description

The Django version used in the current tutorial is 2.0.6.
However, on Django's official website, extended support for the 2.0 series has already expired in April 2019.
https://www.djangoproject.com/download/

I think the Django version used in the Django Girls Tutorial should be LTS 2.2 series. How are you thinking?

There was a similar issue #1536 .

What do I need to do to increase the Django version in the tutorial to 2.2? 
I would love to cooperate.

### Language

Is this related to a specific language of the tutorial?

- English

**Comment by das-g** [comment]
> Why not update the Django version of the tutorial?

Probably no one got around to it, yet. :man_shrugging:

The tutorial is maintained by volunteers like you and me in their free time, so it can happen that some beneficial or even necessary things just don't get done in time.

> However, on Django's official website, extended support for the 2.0 series has already expired in April 2019.
> https://www.djangoproject.com/download/
> 
> I think the Django version used in the Django Girls Tutorial should be LTS 2.2 series. How are you thinking?

Good point! If we can, we should definitely use a still-supported version in the tutorial. As Django 2.2 is both an LTS release _and_ the currently latest release that version seems indeed to be the best choice.

> What do I need to do to increase the Django version in the tutorial to 2.2?

The whole tutorial needs to be tested with the new Django version 2.2.

If everything turns out to still work, we can just change the version number to 2.2. If some of the current code causes deprecation warnings or similar when used with Django 2.2, that code _should_ be adapted to the new version. Current code that doesn't work anymore with Django 2.2 obviously _must_ be updated when we change to the new version number to 2.2 (or optionally even before, if the new variant of the code also works with the currently used version 2.0).

> I would love to cooperate.

Thank you! If you have time to go through the complete tutorial with Django 2.2 and test whether everything is still working, that'd be of great help.

As this issue (#1555) is phrased as a question, I consider it resolved by this answer and close it now. If you disagree, please indicate, so we can re-open it.

I suggest we use #1536 for tracking progress of the transition to Django 2.2. So if you (@kaizumaki or anyone reading this) are going to do the required testing or have already done so, please state that in a comment there. Please also report whether there are any incompatibilities or deprecation warnings you noticed, and if so, which ones.

Once you know all changes needed, please file a pull request with them.

If you know some but not all of the changes needed and would like put them up for discussion, feel free to file a draft pull request.
