### ISSUE TITLE
GitBook Legacy will be shutdown

### ISSUE THREAD

**Issue by magul** [DjangoGirls/tutorial#1652]
![Screenshot from 2020-04-08 21-06-04](https://user-images.githubusercontent.com/1165138/78823658-57715580-79dd-11ea-8283-aeda5fb70dc7.png)

**Comment by das-g** [comment]
Thanks for letting us know. Can you copy in the text as text instead of screenshot, please?

**Comment by magul** [comment]
Sure, I thought about just after posting image.

> Hi Tomasz Magulski,
> We are reaching out to you because after the 30th of April, one year after being deprecated, our legacy version of GitBook, legacy.gitbook.com, will be shutdown.
The brand new app.gitbook.com, now live for more than two years, offers a much better experience for both your readers and your team.
You can learn more about the complete list of differences in our official documentation.
> Since you first signed up to GitBook on May 7th 2017, you have created or contributed to content on legacy.gitbook.com.
Until the 30th of April, you can easily migrate your content in one click to the new version using the banner on your profile at https://legacy.gitbook.com/@magul.
> After the 30th of April, your public content will be archieved and remain accessible using its public URL, but will no longer be accessible on legacy.gitbook.com.
We invite you to read our blog article to learn more about what's new and what remains the same on the new version of GitBook.
> If you are having any trouble migrating your content, we encourage you to reach out to our support team by responding to this email directly, attaching your legacy username magul.
Hoping to see you soon on app.gitbook.com, we wish you all the best.
> Best regards,
> The GitBook team

**Comment by RachellCalhoun** [comment]
Here is some more info about migration: 
https://docs.gitbook.com/resources/gitbook-legacy

**Comment by magul** [comment]
I haven't yet found any information about GitBook legacy to be removed altogether but we need to be aware of #1664 here.

Maybe we should for a time being move hosting from GitBook to GitHub Pages (where static assets will be build on Travis CI). What do you think about that?

@aniav @das-g @RachellCalhoun ?

**Comment by ekohl** [comment]
> Maybe we should for a time being move hosting from GitBook to GitHub Pages (where static assets will be built on Travis CI). What do you think about that?

I don't think we should be using Travis CI. Github Actions are more reliable and faster in my experience.

However, it's probably the quickest way to get back online now. Migrating to modern GitBook might be harder.

**Comment by aniav** [comment]
Last time I checked modern GitBook didn't support plugins which we are using and this was the main blocker. Not sure what would we do with the plugins when moving to GithubPages etc., I also haven't looked into the Django Girls repositories for months, so no idea what's the status now.

**Comment by magul** [comment]
> I don't think we should be using Travis CI. Github Actions are more reliable and faster in my experience.

I proposed Travis CI as we have it right now in place and probably that's something that we need to resolve in a timely manner.

**Comment by magul** [comment]
Ok, it looks that Gitbook have some problems, but we can still use it: https://twitter.com/GitBookStatus/status/1268530219901693956

**Comment by ekohl** [comment]
Looks like there is a fork of gitbook: https://github.com/honkit/honkit. Perhaps that's an easier solution in combination with Github Actions and Github Pages. https://github.com/marketplace/actions/deploy-to-github-pages looks very easy to use.

**Comment by magul** [comment]
I don't recall any upgrade of GitBook CLI in the last three years, so we could continue to use it. The only problem is that GitBook Legacy as a service was shut down. Also, we have Travis CI in place, so to simplify what you suggested @ekohl our stack right now can be easily migrated to:
 * GitBook legacy CLI (still available from npm)
 * Travis CI to build assets (it's already doing it as a measure of checking if everything is ok with source files)
 * GitHub pages (although I'm not a huge fan of pushing outcome to git repo itself, so probably would lean toward something like AWS S3 + CloudFront setup).

**Comment by ekohl** [comment]
So to test this out I created https://github.com/ekohl/tutorial/tree/replace-gitbook-legacy which then deployed to my gh-pages branch automatically (see the Github Actions). That's now deployed at https://ekohl.github.io/tutorial/en/installation/

The downside is that you do have a gh-pages branch that gets larger and larger over time, but it is free and makes it quite trivial to manage. No need for an AWS account and dealing with that. I think it's worth it.

I've submitted #1666 because in my test that was the quickest way to get to the end result.

It also drops Travis CI completely in favor of Github Actions. This reduces the number of services we use which I think is a good thing. I've also recently had a lot of issues with Travis' reliability.

**Comment by ekohl** [comment]
I think per https://github.com/DjangoGirls/tutorial/pull/1666#issuecomment-654332199 this can be closed. Perhaps some account should be deleted there + integration removed. @aniav?

**Comment by aniav** [comment]
We will be able to delete the account there when all our books get moved.

We still have the following hosted on legacy platform:
https://coach.djangogirls.org/
https://faq-organizers.djangogirls.org/
https://organize.djangogirls.org/
https://translate.djangogirls.org/
https://tutorial-extensions.djangogirls.org/

**Comment by ekohl** [comment]
> https://coach.djangogirls.org/
> https://faq-organizers.djangogirls.org/
> https://organize.djangogirls.org/
> https://translate.djangogirls.org/
> https://tutorial-extensions.djangogirls.org/

All of these do not resolve for me right now. It should be easy to copy the same pattern as for the tutorial though.

**Comment by aniav** [comment]
Yes, tutorial is the most complex repo, the other ones should be quick and easy following the same changes. Not sure why these books don't resolve, they have been there for months now 😅

**Comment by ekohl** [comment]
I've seen issues with DNS resolving at GitBook every now and then so perhaps it's just a temporary issue.

**Comment by nikhiljohn10** [comment]
Related to gitbook, have anyone thought about moving to hugo from honkit?

Demo: https://themes.gohugo.io/theme/hugo-book/
Source: https://github.com/gohugoio/hugo
Crowdin Sample: https://github.com/riggy/hugo-crowdin

The tutorial is doing fine. Not necessary to change it. But I feel like we are lagging behind with gitbook legacy since they moved to online editor and all. The change will have lots of bugs to fix and new layout to be created. Once all the Issues and PRs are cleared, we can try something like this.

![image](https://user-images.githubusercontent.com/5616249/99251696-cba58e80-2833-11eb-9845-33528fc2d78e.png)

**Comment by ekohl** [comment]
I think nobody has thought about it, but I wouldn't be opposed. There are certainly a lot of style items that could use improvement.

Note that the tutorial is one of the books. There are also others and we shouldn't diverge them any further.

**Comment by das-g** [comment]
> Related to gitbook, have anyone thought about moving to hugo from honkit?

There are many static site generators to choose from, Hugo being only one of them. Is there anything that would set Hugo apart as particularly suitable for the Django Girls books?

> But I feel like we are lagging behind with gitbook legacy since they moved to online editor and all.

Isn't it the _new_ GitBook system (_not_ GitBook _legacy_) that has the online editor?

If we want the upsides of both, static site generators and online editable CMS, maybe [lektor](https://www.getlektor.com/) would be something to look into. (I've never used it yet, though, so I'm not sure how well-suited it'd be for the documentation- / instruction-natured content of Django Girls' books.)

Some systems for light markup-based static site generation and focused on multi-chapter documentation, that I'm aware of:
- the [Sphinx](https://www.sphinx-doc.org/) / [Read the Docs](https://readthedocs.org/) ecosystem
  - based on the reStructuredText markup language
  - limited(?) support for MarkDown also present
  - well supported by translation platforms like Crowdin or Transifex
- The [AsciiDoctor](https://asciidoctor.org/) / [Antora](https://antora.org/) ecosystem
  - based on the AsciiDoc markup language
  - as far as I can tell, not supported by translation platforms like Crowdin or Transifex
- the GitBook legacy / HonKit ecosystem we're currently using
  - based on the MarkDown markup language
  - support for AsciiDoc in HonKit [also present](https://honkit.netlify.app/syntax/asciidoc.html)

As long as there are no pressing reasons to switch, I'd stick to HonKit or similar GitBook legacy forks, as everything else would require us to
- convert or rewrite our source documents
- change or re-implement many of our established workflows (e.g. translation through crowdin)

That off course shouldn't keep us from evolving our workflows, processes and tooling. But as we don't have the manpower to overhaul everything at once, that probably has to remain limited to (component-by-component) evolution, rather than a revolution that completely switches to a different ecosystem.

**Comment by nikhiljohn10** [comment]
I have just created this website using the new GitBook Online App @ https://app.gitbook.com

https://djangogirls.nikz.in/

( This was made by importing URL from https://tutorial.djangogirls.org/en/. It only has the English translation. Since it was created for demonstration, content is not accurately imported. Need some bug fixing in content.)

Testing, Localisation, Teamwork features etc are not possible without a subscription. There is also a bug in logo uploading. Other than that, everything looks great. Any thoughts? Would there be any ways that we can use it?

**Comment by das-g** [comment]
> Would there be any ways that we can use it?

Why would we want to? As far as I can tell, the non-legacy GitBook is a proprietary platform. Once we adapt to it, we'd be vendor-locked to using it. Using HonkIt or any other FLOSS static page generator we can run ourselves gives us much more freedom and flexibility.

The only upside of non-legacy GitBook I can see is that people can contribute changes more easily, without having to master Git, GitHub and MarkDown. But I'm not sure whether that relative advantage is worth giving up the absolute advantage of retaining full control over our content and revisions thereof.

**Comment by magul** [comment]
Haven't we settled with Github Pages and HonKit?

**Comment by das-g** [comment]
> Haven't we settled with Github Pages and HonKit?

I thought so, yes.

**Comment by nikhiljohn10** [comment]
Got it.
