### ISSUE TITLE
language Needed

### ISSUE THREAD

**Issue by Ayush0230** [DjangoGirls/tutorial#1798]
### Issue description
language need for learning
Describe what's the problem here.
I am an Indian and I need the Hindi language to learn django.
### Language
Hindi
Is this related to a specific language of the tutorial?
yes 
### Operating system
windows

**Comment by das-g** [comment]
Hi @Ayush0230, namaste!

A Hindi translation of the Django Girls tutorial [has been begun](https://crowdin.com/project/django-girls-tutorial/hi) in 2015, but so far, only 9% of the tutorial have been translated to Hindi.¹ Anyone who knows Hindi and English well enough to translate from English to Hindi is welcome to contribute to the translation on Crowdin.

Once the translation is complete, we'll include it on https://tutorial.djangogirls.org

---
¹ Over time actually probably a bit more than that, as changes to the English original invalidate translations of the respective sentences, because they'll have to be re-translated with those changes.

**Comment by Ayush0230** [comment]
Thanks for the reply, I really appreciate it, from INDIA 🇮🇳🇮🇳🇮🇳🇮🇳

**Comment by das-g** [comment]
As this issue isn't actionable until the Hindi translation is complete, and as continuing the translation effort doesn't need to be tracked here, I'm closing this issue for now.
