### ISSUE TITLE
Nicer gitbook plugin for rich-quotes

### ISSUE THREAD

**Issue by olasitarska** [DjangoGirls/tutorial#189]
We're using [gitbook-plugin-richquotes](https://github.com/erixtekila/gitbook-plugin-richquotes) to display warnings, but it's super ugly and it hurts my eyes. Let's make a prettier fork.

**Comment by patjouk** [comment]
They're pretty ugly but could find a better plugin :(

**Comment by jr0cket** [comment]
Instead of richquotes, I am changing over to gitbook-plugin-callouts

The callouts plugin works in a similar way, but look so much better.  You also have a seperate heading and body of the box, so it looks like panels in bootstrap

https://www.npmjs.com/package/gitbook-plugin-callouts

You will need to change > **Hint** to > #### Hint:: in your markdown, but its worth it in my opinion.

> #### Hint::Title of hint (can also leave this blank for a title of Hint)
> Body text...

There are several stiles of panel available

Here is an example from on my own content (work in progress, so beware) 
https://practicalli.github.io/clojurescript/om-project-clojurex/start-the-repl.html

Hope this is helpful.
