### ISSUE TITLE
Source Code Learning

### ISSUE THREAD

**Issue by ahmadina** [DjangoGirls/tutorial#325]
Hi, Is the source code (in book) available for download?
I searched in repository but could not find.

**Comment by ahmadina** [comment]
Can anyone answer my question?

**Comment by aniav** [comment]
Hello @ahmadina. We haven't responded to your question because we are doing Django Girls in our free time and we also wanted to discuss this topic more throughly. Please keep that in mind and give us some more time to answer next time.

We don't have the source code of the resulting project because we think it would not produce any good outcome. The aim of this tutorial is to teach people and help them understand programming, not give them a working app source code.
