### ISSUE TITLE
Too much material covered in the main tutorial

### ISSUE THREAD

**Issue by agagata** [DjangoGirls/tutorial#342]
I feel the tutorial is getting too big.
For most of the attendees, this is their first encounter with terminal, python script, html code etc.
I know there is a lot to be covered. But at the end of the day we don't want the attendees to feel overwhelmed. It's only one day. Yes, you can finish tutorial later at home. But the sense of accomplishment after the workshops will be missing.
There are already some Tutorial Extensions. Why not put some of the chapters from main tutorial there? I was thinking about chapters 19-21, but that's just a suggestion.
Then, the people who finished main tutorial earlier, can do something extra and look through extensions.

I would like to offer a perspective of someone who doesn't consider herself a 'professional programmer' yet. I was an attendee attendee of the first Django Girls workshop in Berlin. Before the workshops, I knew a little bit of Python (the very basics) and had a little bit of experience html and css. Still the workshops were very demanding for me. Just figuring out how django works with all this models, views and urls can be difficult. 
Sorry, if I'm being too personal. Still, I think it is something worth thinking about.

**Comment by kerstin** [comment]
I haven't worked through the updated version of the tutorial yet but I, too, found the original workshop demanding – and I was a 2nd semester CS student with previous HTML, CSS and a little Python knowledge then, so I guess my level was similar to yours? (I actually keep mentioning this whenever I'm asked to compare Rails Girls and Django Girls. ;P)

Sorry for not being able to offer suggestions right now (I really have to redo the tutorial first to be able to do that), I simply wanted to second your sentiment regarding the workshop.

**Comment by keimlink** [comment]
Agata, I agree the tutorial requires the participants to learn a lot of new things on a single (long) day. So the idea to teach only the required basic skills during the first day makes sense.

During the two workshops I supported women learning Django and also from the feedback from other attendees I learned that the previous knowledge is very different which means some participants will complete the tutorial very quickly while others won't finish it during the workshop day. Also having a guide for coaches is great, but still every coach has her/his very own style of teaching, explaining and supporting the group. This are other good reasons for moving as much content as possible to a section with additional exercises.

But I think the chapters 19 and 20 should remain in the basic tutorial because otherwise the blog won't really been complete. But in my opinion it wouldn't be a problem to move the chapters 20 and 21 to a section for additional exercises because they add functionality that is not really required.

I'm curious what other participants  and coaches think about this.

**Comment by aniav** [comment]
I think that the tutorial should stay this way and there are a few reasons for that. The first one is that we don't really have a lot of stuff that is unnecessary in the main tutorial so I am not sure we are able to cut out anything without loss. The second reason: we have different *beginners* levels. We had one group on DG workshops last week that went through the tutorial, github forking/PRs process and then went on to numpy while some others were able to go to templates chapter only and both of these were awesome.

What I would suggest here is adding an information in the coaching manual that the coach should decide if they want to go through the deploy chapter and should make this decision based on how the group is doing.

**Comment by olasitarska** [comment]
I agree with Ania on all except one thing: I think deploy chapter got so much easier recently we should never skip it, it's too important. I'd rather drop forms or "extend your app" chapter than this.

I am also thinking that we should move Domain chapter to extensions, no one is doing that anyway here, right?

**Comment by olasitarska** [comment]
Thanks @aniav!
