### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by lancelote** [DjangoGirls/tutorial#346]
I've finished the Russian translation. But the current crowdin build is 4 weeks dated. Can someone update it, please?

**Comment by asendecka** [comment]
Done! Sorry it took us so long! :sunny:

**Comment by gbezyuk** [comment]
What's current status? It seems like there is still no translation to me, despite that I, in turn, have finished translation on crowdin about a week ago, too. see https://crowdin.com/project/django-girls-tutorial/discussions/29

**Comment by lancelote** [comment]
It should be proofreaded first.

**Comment by olasitarska** [comment]
( :wave: Maybe @rapoulson @tricoder42 can help? )

**Comment by rapoulson** [comment]
Hi @gbezyuk :wave: , my name is Rebecca and I work on translations. Thank you for the work you've done on the Russian tutorial! To assure the quality and longevity of the translations we like to make sure the translation has been thoroughly proofread and vetted by the community prior to release. We also try to make sure that each string has either been translated or proofread by a woman whenever possible. When I see that a string has at least one upvote on it, I manually approve it in Crowdin. I tend not to do this until most of the strings in a section are ready for approval simply because it's easier to avoid missing anything that way. That being said, if there's a workshop or even an individual who needs to use the tutorial immediately, we'll do whatever we can to accelerate this process. I apologize that we don't have this process documented, it's been evolving over the course of the summer but it's definitely time we have something written up publicly so that people know the status of all their hard work.

I'm looking at the Russian translation now, and while I'd still like to have a bit more proofreading coverage on it, perhaps we could discuss doing a beta release for this one this week? It's been in progress for a long time and I'd like y'all to have access to your hard work. What do you think @tricoder42 @olasitarska?

**Comment by olasitarska** [comment]
Makes sense!
