### ISSUE TITLE
github-browsing README leads to 404 at first link

### ISSUE THREAD

**Issue by chadmiller** [DjangoGirls/tutorial#367]
From

https://github.com/DjangoGirls/tutorial

"OK, let's start at the beginning..."

links to https://github.com/DjangoGirls/tutorial/blob/master/how_the_internet_works/README.md , which is not a valid URL.

**Comment by aniav** [comment]
Hello @chadmiller,
links on github may be invalid because they are generated for gitbook and should be checked in tutorial.djangogirls.org. They are relative and preapred specifically for gitbook. Therefore I am closing this issue now. I will try to document the links topic a bit more in the next few days hopefully. Thank you!

**Comment by chadmiller** [comment]
Okay. Maybe the top level README should be for and by the project authors,
and the subject of documentation should be in a lower directory.
