### ISSUE TITLE
Folder / Directory

### ISSUE THREAD

**Issue by helenst** [DjangoGirls/tutorial#373]
The words 'folder' and 'directory' are used interchangeably - I think this can be confusing to a learner, perhaps one should be chosen and used throughout.

**Comment by phalt** [comment]
+1 We should definitely standardise this throughout.

**Comment by aniav** [comment]
Definitelly. Also, there is an issue for creating a glossary, additional description could also be placed there :)

**Comment by aniav** [comment]
Ok. Seconds thoughts. We shouldn't make the naming consistent. The reason why we shouldn't is that girls are going to be working with Stack Overflow afterwards and it is important to prepare them to *the real world* soooo what I think we should do is write that we will be using folder and directory interchangeably :)

**Comment by olasitarska** [comment]
:+1:

**Comment by robcharlwood** [comment]
Looking at this now.

**Comment by kerstin** [comment]
Folders don't really exist though (in a directory structure), the name is only used because that's how directories are visually represented in GUIs, i.e. Windows Explorer. There are no folders on the command line.

(I'm also not sure how interchangeably the terms are really used on sites like Stackoverflow – I'd have guessed that most people use directory over folder.)

Would it make sense to explain this when "directory" is first used and then stick to that term?

**Comment by helenst** [comment]
I agree that directory is a better term to use since we are mostly dealing
with the command line - there are a lot of terms floating around already
and a lot of information for a learner to keep in their head so it makes
sense to stick with one, but it is also worth relating that back to any
previous concept of folders they may have.
