### ISSUE TITLE
Add git installation instructions for older OS X versions

### ISSUE THREAD

**Issue by treyhunner** [DjangoGirls/tutorial#400]
During the Ensenada event, one student had trouble installing Git on Mac OS X 10.8 (Mountain Lion).  @andyosuna resolved the problem by installing Git 2.2.1 snow leopard which, from my understanding, works on 10.6, 10.7, and 10.8.

It might be nice to have git installation instructions on older OS X machines explained or linked to in the tutorial in case another student has a similar issue.

I do not plan to author a pull request because I am not familiar with Mac installation instructions.

**Comment by aniav** [comment]
@andyosuna do you, by any chance, remember what was the problem when installing git on an older version? The [README](http://sourceforge.net/projects/git-osx-installer/files/) states the newest build should work on older versions of OS X and I am not sure how to describe the information on who should look for a different versions. Thank you! :)

**Comment by aniav** [comment]
I have looked the topic through and it seems that had to be a problem with something else, not git itself. The git install states it should just work with older versions of OS X and I can't really find the information that it won't work on some older version. I'm closing that for now because we can't really do anything special about that.

**Comment by andyosuna** [comment]
It was a problem similar to this: http://stackoverflow.com/questions/24215564/installing-git-on-mac-os-10-7-5
And it was resolved by going to sourceforge directly and installing the proper version. The problem appears on OSX 10.7 and before.
For 10.7 and 10.6 install version 2.2.1
You used to be able to install a different version for 10.5, but I suppose there is no longer compatibility or they simply removed those files from the sourceforge page.

http://sourceforge.net/projects/git-osx-installer/files/

P.S. I'm doing this because I saw someone went through this too, in slack.
