### ISSUE TITLE
Different Spanish version in Online docs and crowdin

### ISSUE THREAD

**Issue by humitos** [DjangoGirls/tutorial#402]
Hi all!

I found this sentence in: http://tutorial.djangogirls.org/es/index.html

`Bueno, Tenemos buenas noticias para ti! programar no es tan difícil como aparenta y queremos mostrarte cuán divertido que puede llegar a ser.`

but in: https://crowdin.com/translate/django-girls-tutorial/51/en-es

`Bueno, ¡tenemos buenas noticias para ti! programar no es tan difícil como aparenta y queremos mostrarte cuán divertido puede llegar a ser.`

In fact, the correct version is the second one.

How can we do to update the HTML version?

**Comment by tricoder42** [comment]
Hi @humitos,
the process of updating translation and submitting PR is described in http://translate.djangogirls.org/when_its_ready.html.

It's a bit complicated, I know, but we're working on making it as simple as possible. 

Anyway, thank you for report! :rocket:

**Comment by kerstin** [comment]
@tricoder42 The guide doesn't explain how to update or extend existing translations. If the process is exactly the same, I think this needs to be mentioned. While proofreading it, I assumed it was meant for first-time translations only.

I've seen people correct mistakes in translations via git, and was wondering how that works because in previous projects I've been involved in, all future edits also had to be done in the translation software.

**Comment by humitos** [comment]
@tricoder42 Ok, this link from the guide doesn't work (https://crowdin.com/project/django-girls-tutorial/settings#translations). I'm getting 404:

```
Go to the Crowdin settings page.
```

I could do that, but I need extra permissions and the correct link :)

**Comment by tricoder42** [comment]
@kerstin Yes, the process is the same. I'll update translation guidelines soon. Thx :rose: 
@humitos Are you logged in? The link works for me, so if it's a permission problem, I'll do that for you. :rocket: 

Thank you both! :sunflower: :sunny: :sunglasses:

**Comment by lhuriguen** [comment]
Hey there! Any progress on this? If you need help, I could take care of it if you give me permission on Crowdin :innocent:

**Comment by humitos** [comment]
@tricoder42 Yes, it seems that it's a permission problem:

```
Project does not exist or access to this project is limited.
```

Can you give privileges on this?

**Comment by rapoulson** [comment]
Hi folks!:wave: @tricoder42 and I are currently in the process of revamping/formalizing the way we handle translations. We're sorry for any confusion that's happening while we're figuring things out--new docs are coming soon--promise :grinning:! We're moving towards amping up our proofreading and beta period prior to official release and keeping those releases stable for a longer time (translations will be better (yay! :tada:) but they won't keep pace with every change to the English version and @tricoder42 and I will probably be the only ones who have to deal with Gitbook for translations which, trust me, is a good thing :stuck_out_tongue_winking_eye: ). We'll be putting out a PR regarding the new process soon and we welcome feedback from awesome translators like yourselves!

As for the Spanish tutorial, specifically, now is a great time to contribute! We're in the proofreading phase for a new release which we hope to launch a beta version of around July 15th so that it's available for Django Girls Bilbao on July 20th. During this time, the best way to help is to vote on/suggest revisions to translations via Crowdin--you can also email us with any thoughts/questions at translations@djangogirls.org :es: :confetti_ball:

**Comment by lhuriguen** [comment]
Thanks Rebecca! I'll be coaching at Bilbao and that was exactly my concern. I should have known better, you guys are amazing! :clap: :smile:
