### ISSUE TITLE
Clarify need to create posts in PythonAnywhere

### ISSUE THREAD

**Issue by lightstrike** [DjangoGirls/tutorial#469]
In workshops I've attended, I have a noticed a common point of confusion is recognizing local versus remote (PythonAnywhere) databases ("why aren't the posts I already created on PythonAnywhere?"). It would be helpful to add/clarify prompts to make sure creating/updating Post objects (such as adding published_date after adding list filter to views.py) is done both locally and remotely.

**Comment by treyhunner** [comment]
:+1: this required extra clarification for all three of my students yesterday

I heard other coaches mention two solutions:

1. Copying the local `db.sqlite3` contents to Python Anywhere outside of git (I'm not sure whether this was a file upload of a dump/load)
2. Manually inputting posts again from the admin interface or from the shell on PythonAnywhere

**Comment by olasitarska** [comment]
I understand that [this](https://github.com/DjangoGirls/tutorial/pull/444/files#diff-733b3a4f3942013e4c0f308cd2a471acR50) didn't help?

If not, then I'm in favor of the second solution @treyhunner! :)

**Comment by treyhunner** [comment]
@olasitarska ah I assumed they missed a blurb like that one but we didn't manage to spot it.

I think further clarification would help (preferably clarifying the second option before the point where we expect posts to appear remotely).

**Comment by olasitarska** [comment]
Go for it ;)

**Comment by bmispelon** [comment]
Suggestion by @HonzaKral which I think makes sense (especially if it's done as an extra step showing its impact):

Use PythonAnywhere's file upload feature to copy the sqlite database from the user's machine to the server.

**Comment by rsip22** [comment]
Since we are talking about this, I think it could also be mentioned in the tutorial that the posts created locally are just a "test drive" of sorts and the final ones will be created once we put the blog on the server. Just because I've seen some girls "wasting" a lot of time and dedicated themselves to write these posts just to be disappointed that the website was blank and they had to do them all over again once it was deployed.

**Comment by MisterRios** [comment]
I had this same issue at the last workshop I coached at and had to think about it for a second. Mostly because my suggestion was going to be a datadump to JSON but wasn't sure that it was within the scope of the tutorial. I think @bmispelon 's suggestion to copy the sqlite database is a great idea, but this is also something that is never done. At least not in this way.

In the end I explained that even though the code was the same, the databases lived in different machines. I ended up suggesting opening two windows side by side and copy and pasting.

It speaks to the psychology of beginner coders. You've worked so hard to produce something that you just don't want to throw it away, even though throwing away code/content is super common. 

Has anyone worked on this? May I? I think the copy and paste approach would be better since it reinforces that the databases live on different systems. Any further thoughts?

**Comment by rsip22** [comment]
I think [this](https://github.com/DjangoGirls/tutorial/pull/444/files#diff-733b3a4f3942013e4c0f308cd2a471acR50), which @olasitarska mentioned, helps a bit, but I couldn't help but notice it is mentioned _after_ they've created all the posts (they usually do that when they log into admin, in the previous chapter).

I also think further clarification would be good, @MisterRios

**Comment by aniav** [comment]
I honestly think this explanation is very through and I think we don't really need more explanation. I would not add explanation in the admin chapter about the deployment process because not all groups go through deployment process. Some groups decidoe to skip it. I Am closing that for now, feel free to open it at any point you feel we need something more. Thank you all! 🎉
