### ISSUE TITLE
Cliff hanger not appreciated in a tutorial

### ISSUE THREAD

**Issue by xyzisinus** [DjangoGirls/tutorial#490]
The tutorial I used as of 10/10/2015 has an interesting habit of ending a chapter (chapter 13 and 14) on an error case, leaving the fix to the next chapter.  Suspense is an important technique in literature, but not in tutorial writing.  An already anxious student can only be further intimidated.

**Comment by olasitarska** [comment]
Good sugestion. Would love to see a pull request for that! :)

**Comment by jhodgdon-drp** [comment]
One example of where this is happening is at the end of the "Django urls" chapter. You make a file called urls.py and put something in it for the home page saying "Use this view" but don't create the view. Then you're instructed to try to visit the home page, where you get nothing because of the error. The next chapter explains how to fix the error.

I guess the solution in this case would be to move the section about visiting the home page to the next chapter?

**Comment by goanpeca** [comment]
I think chapters should somehow build upon previous chapters but be by themselves something that is self contained. If an attendee stops somewhere, I wants to start, it will naturally go towards the beginning of the chapter, so having to "solve" the cliffhanger might also affect the flow. I am in favor of removing cliffhangers as well.

It is really discouraging to finish on an error no matter how many times you emphasize that errors are not to be feared.

**Comment by fltfx** [comment]
Closing this as tutorial has changed a lot since 2018, I assume. if still an issue, we can reopen.
