### ISSUE TITLE
Sample command / output boxes should visually differentiate prompt, command and output

### ISSUE THREAD

**Issue by funkybob** [DjangoGirls/tutorial#945]
As we're running DjangoGirls Melbourne, we're finding a very common problem is people not recognising the difference between prompt, command and expected output from the sample blocks.

I'd recommend using colours.

Probably would also help to explain the $ means "this happens at the command prompt", as many people are confused about what to type where.

**Comment by helenst** [comment]
Hi @funkybob this was previously discussed in (#191) and the problem seems to be that highlightjs (which is the highlighting system used by gitbook) doesn't support highlighting of bash prompt sessions. pygments does so maybe https://www.npmjs.com/package/gitbook-plugin-pygments is a way forward? I think colours are a good idea, regardless of the explanations being there.

**Comment by codehakase** [comment]
@funkybob sorry about the hassle there, hope you'll enjoy using Django

**Comment by aniav** [comment]
Since you first opened this issue @funkybob the tutorial has gained title boxes which state if something is a command-line or anything else. We also define what `$` and `>` are so I will close that for now. Feel free to reopen any time! 👍
