### ISSUE TITLE
virtual env within django code folder

### ISSUE THREAD

**Issue by teelee7133** [DjangoGirls/tutorial#999]
it seems to me that after following instructions, the virtual env folder will be within django blog code folder, like

djangogirls/
    manage.py
    mysite/  
    myverv/

if I am not mistaken, we could update 'your first Django project', or maybe separate 'myverv' into another folder?

thanks!

**Comment by aniav** [comment]
Hey @teelee7133, I am not sure what is the problem here. The `myvenv` directory is created within `djangogirls` folder, this is the expected behaviour as we want the whole of Django Girls tutorial in one place. This also not an uncommon pattern to follow. I am therefeore closing this issue for now, but feel free to comment further with issues :)
